### ISSUE TITLE
First level of tree always empty

### ISSUE THREAD

**Issue by springmeyer** [mapsam/callgraph#6]
I uploaded my first callgraph (https://callgraph.herokuapp.com/78036c345a8891cbfdc5e2889ad312d1#thread-8) and am noticing that the first item in a tree seems to open to nothing. Perhaps that is correct, or perhaps a display bug?

**Comment by springmeyer** [comment]
![screen shot 2017-11-09 at 5 29 31 pm](https://user-images.githubusercontent.com/20300/32638311-91f42d52-c573-11e7-95ad-46674a0de805.png)


Looking closer I would expect `pthread_body` here to have data when open. It looks like the problem is the nesting: `uv_thread_start` should be displayed only when `pthread_body` is open and within it.

Here is the equivalent in Activity monitor:

![screen shot 2017-11-09 at 5 31 13 pm](https://user-images.githubusercontent.com/20300/32638367-cf1ce296-c573-11e7-8434-ad8bfc4b9318.png)

**Comment by mapsam** [comment]
Thanks @springmeyer! Looks like you're right - I'd guess something incorrect with the way we're creating a markdown list from the original callgraph, less likely something incorrect with the markdown parser library.

**Comment by mapsam** [comment]
Looks like the markdown list is formatted correctly, so perhaps this is an issue with the markdown parsing:

```
 * `2328 start  (in node) + 52  [0x100000a34]`
   * `2328 node::Start(int, char**)  (in node) + 583  [0x100667fbb]`
     * `2328 uv_run  (in node) + 321  [0x10078c1bb]`
       * `2328 uv__io_poll  (in node) + 1554  [0x10079a9fa]`
         * `2328 uv__async_io  (in node) + 136  [0x10078bd08]`
           * `2328 uv__async_event  (in node) + 198  [0x10078bb75]`
             * `2328 uv__work_done  (in node) + 178  [0x100789f69]`
               * `2211 VectorTileQuery::Worker::~Worker()  (in vtquery.node) + 14  [0x1016c7e0e]`
                 * `1840 VectorTileQuery::Worker::~Worker()  (in vtquery.node) + 146  [0x1016ca182]`
                   * `1352 free_tiny  (in libsystem_malloc.dylib) + 343  [0x7fffc169bf8d]`
                     * `1347 _os_unfair_lock_lock_slow  (in libsystem_platform.dylib) + 130  [0x7fffc17143d2]`
                       * `1343 _os_ulock_wait  (in libsystem_platform.dylib) + 25  [0x7fffc1714aff]`
                         * `1343 __ulock_wait  (in libsystem_kernel.dylib) + 10  [0x7fffc163131e]`
                       * `4 _os_ulock_wait  (in libsystem_platform.dylib) + 25  [0x7fffc1714aff]`
                     * `5 _os_unfair_lock_lock_slow  (in libsystem_platform.dylib) + 125,77,...  [0x7fffc17143cd,0x7fffc171439d,...]`
                   * `165 szone_size  (in libsystem_malloc.dylib) + 222,100,...  [0x7fffc16860c5,0x7fffc168604b,...]`
                   * `146 _os_unfair_lock_unlock_slow  (in libsystem_platform.dylib) + 42  [0x7fffc17144a4]`
                     * `141 _os_ulock_wake  (in libsystem_platform.dylib) + 17  [0x7fffc1714baa]`
                       * `141 __ulock_wake  (in libsystem_kernel.dylib) + 10,20  [0x7fffc1631336,0x7fffc1631340]`
                     * `5 _os_ulock_wake  (in libsystem_platform.dylib) + 17,40  [0x7fffc1714baa,0x7fffc1714bc1]`
                   * `63 free_tiny  (in libsystem_malloc.dylib) + 671  [0x7fffc169c0d5]`
                     * `30 tiny_free_no_lock  (in libsystem_malloc.dylib) + 2455,417,...  [0x7fffc169bcdf,0x7fffc169b4e9,...]`
                     * `19 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1484  [0x7fffc169b914]`
                       * `19 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 231,43,...  [0x7fffc1686ed0,0x7fffc1686e14,...]`
                     * `4 tiny_free_no_lock  (in libsystem_malloc.dylib) + 80  [0x7fffc169b398]`
                       * `4 get_tiny_previous_free_msize  (in libsystem_malloc.dylib) + 63,47,...  [0x7fffc16865dd,0x7fffc16865cd,...]`
                     * `3 tiny_free_list_add_ptr  (in libsystem_malloc.dylib) + 31,26,...  [0x7fffc1686606,0x7fffc1686601,...]`
                     * `3 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1050  [0x7fffc169b762]`
                       * `3 get_tiny_free_size  (in libsystem_malloc.dylib) + 72,33  [0x7fffc1686de5,0x7fffc1686dbe]`
                     * `2 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1392  [0x7fffc169b8b8]`
                       * `2 get_tiny_free_size  (in libsystem_malloc.dylib) + 72  [0x7fffc1686de5]`
                     * `2 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1533  [0x7fffc169b945]`
                       * `2 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 231  [0x7fffc1686ed0]`
                   * `55 free_tiny  (in libsystem_malloc.dylib) + 691,321,...  [0x7fffc169c0e9,0x7fffc169bf77,...]
```

Here's the output HTML

```
<ul>
    <li><code>2328 start  (in node) + 52  [0x100000a34]</code>
        <ul>
            <li><code>2328 node::Start(int, char**)  (in node) + 583  [0x100667fbb]</code>
                <ul>
                    <li><code>2328 uv_run  (in node) + 321  [0x10078c1bb]</code></li>
                    <li><code>2328 uv__io_poll  (in node) + 1554  [0x10079a9fa]</code>
                        <ul>
                            <li><code>2328 uv__async_io  (in node) + 136  [0x10078bd08]</code></li>
                            <li><code>2328 uv__async_event  (in node) + 198  [0x10078bb75]</code>
                                <ul>
                                    <li><code>2328 uv__work_done  (in node) + 178  [0x100789f69]</code></li>
                                    <li><code>2211 VectorTileQuery::Worker::~Worker()  (in vtquery.node) + 14  [0x1016c7e0e]</code>
                                        <ul>
                                            <li><code>1840 VectorTileQuery::Worker::~Worker()  (in vtquery.node) + 146  [0x1016ca182]</code></li>
                                            <li><code>1352 free_tiny  (in libsystem_malloc.dylib) + 343  [0x7fffc169bf8d]</code>
                                                <ul>
                                                    <li><code>1347 _os_unfair_lock_lock_slow  (in libsystem_platform.dylib) + 130  [0x7fffc17143d2]</code></li>
                                                    <li><code>1343 _os_ulock_wait  (in libsystem_platform.dylib) + 25  [0x7fffc1714aff]</code>
                                                        <ul>
                                                            <li><code>1343 __ulock_wait  (in libsystem_kernel.dylib) + 10  [0x7fffc163131e]</code></li>
                                                        </ul>
                                                    </li>
                                                    <li><code>4 _os_ulock_wait  (in libsystem_platform.dylib) + 25  [0x7fffc1714aff]</code></li>
                                                    <li><code>5 _os_unfair_lock_lock_slow  (in libsystem_platform.dylib) + 125,77,...  [0x7fffc17143cd,0x7fffc171439d,...]</code></li>
                                                </ul>
                                            </li>
                                            <li><code>165 szone_size  (in libsystem_malloc.dylib) + 222,100,...  [0x7fffc16860c5,0x7fffc168604b,...]</code></li>
                                            <li><code>146 _os_unfair_lock_unlock_slow  (in libsystem_platform.dylib) + 42  [0x7fffc17144a4]</code>
                                                <ul>
                                                    <li><code>141 _os_ulock_wake  (in libsystem_platform.dylib) + 17  [0x7fffc1714baa]</code></li>
                                                    <li><code>141 __ulock_wake  (in libsystem_kernel.dylib) + 10,20  [0x7fffc1631336,0x7fffc1631340]</code></li>
                                                    <li><code>5 _os_ulock_wake  (in libsystem_platform.dylib) + 17,40  [0x7fffc1714baa,0x7fffc1714bc1]</code></li>
                                                </ul>
                                            </li>
                                            <li><code>63 free_tiny  (in libsystem_malloc.dylib) + 671  [0x7fffc169c0d5]</code>
                                                <ul>
                                                    <li><code>30 tiny_free_no_lock  (in libsystem_malloc.dylib) + 2455,417,...  [0x7fffc169bcdf,0x7fffc169b4e9,...]</code></li>
                                                    <li><code>19 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1484  [0x7fffc169b914]</code></li>
                                                    <li><code>19 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 231,43,...  [0x7fffc1686ed0,0x7fffc1686e14,...]</code></li>
                                                    <li><code>4 tiny_free_no_lock  (in libsystem_malloc.dylib) + 80  [0x7fffc169b398]</code></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
```

**Comment by mapsam** [comment]
Looks like some of the `<li>` are just combined ... so this is an issue with the markdown parsing. It appears the npm library I'm using isn't maintained any longer. https://github.com/evilstreak/markdown-js/issues/266

Will try another few options to see if that resolves it.

**Comment by mapsam** [comment]
This has been fixed! @springmeyer want to give it another whirl? 

![screen shot 2017-11-17 at 4 17 52 pm](https://user-images.githubusercontent.com/1943001/32974436-edd60d94-cbb2-11e7-9cc0-fb119067cfc6.png)

**Comment by springmeyer** [comment]
@mapsam thanks! I tested at https://callgraph.herokuapp.com/ and am still seeing a problem, however. Would you expect the code at heroku to be updated yet? (I've only used that and not run locally yet).

For reference what I'm seeing, you should be able to replicate with https://gist.github.com/springmeyer/b0517f9f6bce1c916d22064f4452969f. Notice that the last thread of that looks like:

```
 2124 Thread_2474442
      2120 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fffc290d08d]
      ! 2120 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fffc290d887]
      !   2120 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fffc290d93b]
      !     2120 uv__thread_start  (in node) + 25  [0x1007922b0]
```

So, `pthread` should be within the `thread_start` like:

![screen shot 2017-11-17 at 4 39 54 pm](https://user-images.githubusercontent.com/20300/32974791-f8526c60-cbb5-11e7-8c4f-3aa1c13c584d.png)

However I'm not seeing that nesting at the heroku site:

![screen shot 2017-11-17 at 4 39 32 pm](https://user-images.githubusercontent.com/20300/32974799-09be7796-cbb6-11e7-8e3a-168428d72ffe.png)

**Comment by mapsam** [comment]
Hmm, I think that's just a problem with the final thread. Its syntax is a bit different than every other thread (ugh). I'm going to open a separate ticket for that, since it's less about the `<li>` nesting and more about the unique parsing.

**Comment by springmeyer** [comment]
Thanks @mapsam - works great now (just tested one last time on the live version). 🙌
